using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace YgomSystem.UI
{
	public class FreeTextFilter : MonoBehaviour
	{
		private FreeTextFilterCache m_FreeTextFilterCache;

		private MDText m_TargetText;

		private TMP_Text m_TargetTMPText;

		private string m_FreeText;

		private void SetText(string text)
		{
		}

		private void OnDestroy()
		{
		}

		public void SetFreeText(string freeText)
		{
		}

		public void OnFilteredFreeText(string freeText, string filteredFreeText)
		{
		}
	}
}
