using System.Collections;
using System.Text;
using UnityEngine;
using UnityEngine.UI;
using YgomSystem.ElementSystem;

public class TextLoadResearch : MonoBehaviour
{
	private ElementObjectManager _eom;

	private MDText _msg;

	private StringBuilder _buffer;

	private void AddLine(string text)
	{
	}

	private void TextClear()
	{
	}

	private void Awake()
	{
	}

	private IEnumerator Start()
	{
		return null;
	}

	private void Measure<T>()
	{
	}

	private IEnumerator Exec()
	{
		return null;
	}
}
