using UnityEngine;
//using UnityEngine.EventSystems;
using UnityEngine.UI;

namespace YgomGame.Home
{
	public class CircleLayoutGroup// : UIBehaviour, ILayoutGroup, ILayoutController
	{
		[SerializeField]
		private float radius;

		[SerializeField]
		private float arc;

		[SerializeField]
		private float offsetAngle;

		[SerializeField]
		private Vector2 space;

		[SerializeField]
		private bool reverse;

		public void SetLayoutHorizontal()
		{
		}

		public void SetLayoutVertical()
		{
		}

		private void SetCircleLayout()
		{
		}
	}
}
